# Generated by Django 3.1 on 2020-08-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.BooleanField()),
                ('content', models.CharField(max_length=200)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('post_time', models.DateTimeField()),
            ],
        ),
    ]
