# Generated by Django 3.1 on 2020-08-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_time']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
